version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/natlas-server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/natlas-server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/natlas-server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/natlas-agent"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/natlas-agent"
    schedule:
      interval: "weekly"
