version: "2"
plugins:
  eslint:
    enabled: true
    channel: eslint-6
    config:
      config: ./natlas-server/.eslintrc.yml
  tslint:
      enabled: true
      config: ./natlas-server/tslint.json
  stylelint:
    enabled: true
    config: ./natlas-server/.stylelintrc.yml
  pep8:
    enabled: true
    checks:
      E402:
        enabled: false
      E203:
        enabled: false
      W503:
        enabled: false
    exclude_patterns:
    # machine generated, duplication likely
    - "natlas-server/migrations/versions/"
  radon:
    enabled: true
    config:
      python_version: 3
  shellcheck:
    enabled: true
  sonar-python:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - python:
          python_version: 3
    exclude_patterns:
    # machine generated, duplication likely
    - "natlas-server/migrations/versions/"
