[project]
name = "natlas"
requires-python = "==3.11"

[tool.ruff]

[tool.ruff.lint]
select = [
    # flake8-bugbear
    "B",
    # flake8-comprehensions
    "C4",
    # pyflakes
    "F",
    # flynt
    "FLY",
    # isort
    "I",
    # pylint
    "PL",
    # Ruff's own rules
    "RUF",
    # flake8-simplify
    "SIM",
    # flake8-tidy-imports
    "TID",
    # pyupgrade
    "UP",
]
ignore = [
    "PLR2004",
    "PLR0912",
    "PLR0911",
    "PLR0915",
    "PLC0414"
]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"
