[project]
name = "natlas"
requires-python = "==3.11"

[tool.ruff]

[tool.ruff.lint]
select = [
    # flake8-bugbear
    "B",
    # flake8-comprehensions
    "C4",
    # isort
    "I",
    # Ruff's own rules
    "RUF",
    # flake8-simplify
    "SIM",
    # flake8-tidy-imports
    "TID",
    # pyupgrade
    "UP",
]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"
