extends: stylelint-config-standard-scss
plugins:
  - stylelint-scss
syntax: scss

ignoreFiles:
  - "**/vendor/*.css"
  - "**/vendor/*.js"

rules:
  color-no-invalid-hex: true
  at-rule-no-unknown: [true,
    {
      ignoreAtRules: [
        "tailwind",
        "apply",
        "variants",
        "responsive",
        "screen",
        "use",
        "mixin",
        "include",
      ]
    }
  ]
  scss/at-rule-no-unknown: [true,
    {
      ignoreAtRules: [
        "tailwind",
        "apply",
        "variants",
        "responsive",
        "screen"
      ]
    }
  ]
  selector-class-pattern: null
  selector-id-pattern: null
