# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-03 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan_manager', '0006_auto_20151225_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
