"""Make fields not nullable

Revision ID: 26d2ee2d52bf
Revises: 27542c0e6bd8
Create Date: 2025-01-17 08:24:56.988416

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "26d2ee2d52bf"
down_revision = "27542c0e6bd8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agent_config", schema=None) as batch_op:
        batch_op.alter_column(
            "versionDetection", existing_type=sa.BOOLEAN(), nullable=False
        )
        batch_op.alter_column("osDetection", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column(
            "enableScripts", existing_type=sa.BOOLEAN(), nullable=False
        )
        batch_op.alter_column("onlyOpens", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column("scanTimeout", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column(
            "webScreenshots", existing_type=sa.BOOLEAN(), nullable=False
        )
        batch_op.alter_column(
            "vncScreenshots", existing_type=sa.BOOLEAN(), nullable=False
        )
        batch_op.alter_column(
            "webScreenshotTimeout", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "vncScreenshotTimeout", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "scriptTimeout", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column("hostTimeout", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("osScanLimit", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column("noPing", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column("udpScan", existing_type=sa.BOOLEAN(), nullable=False)

    with op.batch_alter_table("natlas_services", schema=None) as batch_op:
        batch_op.alter_column(
            "sha256", existing_type=sa.VARCHAR(length=64), nullable=False
        )
        batch_op.alter_column("services", existing_type=sa.TEXT(), nullable=False)

    with op.batch_alter_table("scope_item", schema=None) as batch_op:
        batch_op.drop_constraint("scope_item_target_key", type_="unique")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scope_item", schema=None) as batch_op:
        batch_op.create_unique_constraint("scope_item_target_key", ["target"])

    with op.batch_alter_table("natlas_services", schema=None) as batch_op:
        batch_op.alter_column("services", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column(
            "sha256", existing_type=sa.VARCHAR(length=64), nullable=True
        )

    with op.batch_alter_table("agent_config", schema=None) as batch_op:
        batch_op.alter_column("udpScan", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column("noPing", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column("osScanLimit", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column("hostTimeout", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column(
            "scriptTimeout", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column(
            "vncScreenshotTimeout", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column(
            "webScreenshotTimeout", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column(
            "vncScreenshots", existing_type=sa.BOOLEAN(), nullable=True
        )
        batch_op.alter_column(
            "webScreenshots", existing_type=sa.BOOLEAN(), nullable=True
        )
        batch_op.alter_column("scanTimeout", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("onlyOpens", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column(
            "enableScripts", existing_type=sa.BOOLEAN(), nullable=True
        )
        batch_op.alter_column("osDetection", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column(
            "versionDetection", existing_type=sa.BOOLEAN(), nullable=True
        )

    # ### end Alembic commands ###
