"""NatlasServices table

Revision ID: 7d9abd1be32c
Revises: 3fb710fe0fe1
Create Date: 2019-02-07 03:00:36.999599

"""

import hashlib
import os

from alembic import op
import sqlalchemy as sa

from config import Config

# revision identifiers, used by Alembic.
revision = "7d9abd1be32c"
down_revision = "3fb710fe0fe1"
branch_labels = None
depends_on = None


def get_default_services():
    record = {"id": 1, "sha256": "", "services": ""}
    with open(os.path.join(Config().BASEDIR, "defaults/natlas-services")) as f:
        record["services"] = f.read().rstrip("\r\n")
    record["sha256"] = hashlib.sha256(record["services"].encode()).hexdigest()
    return record


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    services_table = op.create_table(
        "natlas_services",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("services", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
    # Insert default natlas services file
    op.bulk_insert(services_table, [get_default_services()])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("natlas_services")
    # ### end Alembic commands ###
