"""Add ScopeLogs to db

Revision ID: 9b9fdebcdcb8
Revises: 6147093c140b
Create Date: 2020-03-06 23:30:12.032061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9b9fdebcdcb8"
down_revision = "6147093c140b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scope_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("msg", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scope_log")
    # ### end Alembic commands ###
