"""Move scripts to agent config

Revision ID: b8c40d66be2b
Revises: 26d2ee2d52bf
Create Date: 2025-02-17 22:02:56.278242

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import Session
from sqlalchemy.sql import column, table

# revision identifiers, used by Alembic.
revision = "b8c40d66be2b"
down_revision = "26d2ee2d52bf"
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    session = Session(bind=bind)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agent_script", schema=None) as batch_op:
        batch_op.drop_index("ix_agent_script_name")

    op.drop_table("agent_script")
    with op.batch_alter_table("agent_config", schema=None) as batch_op:
        batch_op.add_column(sa.Column("scripts", sa.ARRAY(sa.String()), nullable=True))

    agent_config_table = table("agent_config", column("scripts", sa.ARRAY(sa.String())))
    session.execute(sa.update(agent_config_table).values(scripts=["default"]))
    session.commit()

    with op.batch_alter_table("agent_config", schema=None) as batch_op:
        batch_op.alter_column("scripts", nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agent_config", schema=None) as batch_op:
        batch_op.drop_column("scripts")

    op.create_table(
        "agent_script",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=128), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="agent_script_pkey"),
    )
    with op.batch_alter_table("agent_script", schema=None) as batch_op:
        batch_op.create_index("ix_agent_script_name", ["name"], unique=True)

    # ### end Alembic commands ###
