extends: stylelint-config-standard-scss
plugins:
  - stylelint-scss
syntax: scss
rules:
  color-no-invalid-hex: true
  at-rule-no-unknown: [true,
    {
      ignoreAtRules: [
        "tailwind",
        "apply",
        "variants",
        "responsive",
        "screen"
      ]
    }
  ]
  scss/at-rule-no-unknown: [true,
    {
      ignoreAtRules: [
        "tailwind",
        "apply",
        "variants",
        "responsive",
        "screen"
      ]
    }
  ]
  selector-class-pattern: null
  selector-id-pattern: null
