"""empty message

Revision ID: 271044238ee1
Revises: ed2f92f790d3
Create Date: 2018-06-07 11:17:38.319471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '271044238ee1'
down_revision = 'ed2f92f790d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
