name: CI

concurrency:
  group: pr-${{github.event.pull_request.number}}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch: # Allow manual triggering

env:
  DEFAULT_BRANCH: main
  IS_DEFAULT_BRANCH: ${{ github.ref == 'refs/heads/main' }}
  PYTHON_VERSION: 3.11

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: ./.github/actions/fetch
        with:
          ref: ${{ env.DEFAULT_BRANCH }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install pre-commit
        run: |
          pip install --disable-pip-version-check --no-compile pre-commit

      - name: Run pre-commit checks
        run: |
          pre-commit run --show-diff-on-failure --color=always --from-ref ${{ env.DEFAULT_BRANCH }} --to-ref HEAD
  required:
    runs-on: ubuntu-latest
    needs:
      - pre-commit
    steps:
      - name: Ensure all jobs required for CI pass
        run: |
          echo "All required jobs have passed."
